# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [12]:
!jupyter nbextension enable --py --sys-prefix widgetsnbextension
!pip install gmaps
!jupyter nbextension enable --py --sys-prefix gmaps

Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
Requirement already satisfied: gmaps in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (0.9.0)
Requirement already satisfied: six in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from gmaps) (1.14.0)
Requirement already satisfied: traitlets>=4.3.0 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from gmaps) (4.3.3)
Requirement already satisfied: ipython>=5.3.0 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from gmaps) (7.13.0)
Requirement already satisfied: ipywidgets>=7.0.0 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from gmaps) (7.5.1)
Requirement already satisfied: geojson>=2.0.0 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from gmaps) (2.5.0)
Requirement already satisfied: ipython-genutils in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from traitlets>=4.3.0->gmaps) (0.2.0)
Requirement already satisfied: decorator in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from traitlets>=4.3.0->gmaps) (4.4.2)
Requirement already satisfied: setuptools>=18.5 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from ipython>=5.3.0->gmaps) (46.1.3.post20200330)
Requirement already satisfied: backcall in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from ipython>=5.3.0->gmaps) (0.1.0)
Requirement already satisfied: pygments in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from ipython>=5.3.0->gmaps) (2.6.1)
Requirement already satisfied: appnope; sys_platform == "darwin" in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from ipython>=5.3.0->gmaps) (0.1.0)
Requirement already satisfied: pexpect; sys_platform != "win32" in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from ipython>=5.3.0->gmaps) (4.8.0)
Requirement already satisfied: pickleshare in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from ipython>=5.3.0->gmaps) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from ipython>=5.3.0->gmaps) (3.0.4)
Requirement already satisfied: jedi>=0.10 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from ipython>=5.3.0->gmaps) (0.15.2)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from ipywidgets>=7.0.0->gmaps) (3.5.1)
Requirement already satisfied: ipykernel>=4.5.1 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from ipywidgets>=7.0.0->gmaps) (5.1.4)
Requirement already satisfied: nbformat>=4.2.0 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from ipywidgets>=7.0.0->gmaps) (5.0.4)
Requirement already satisfied: ptyprocess>=0.5 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from pexpect; sys_platform != "win32"->ipython>=5.3.0->gmaps) (0.6.0)
Requirement already satisfied: wcwidth in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=5.3.0->gmaps) (0.1.9)
Requirement already satisfied: parso>=0.5.2 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from jedi>=0.10->ipython>=5.3.0->gmaps) (0.5.2)
Requirement already satisfied: notebook>=4.4.1 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (6.0.3)
Requirement already satisfied: jupyter-client in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (6.1.2)
Requirement already satisfied: tornado>=4.2 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (6.0.4)
Requirement already satisfied: jupyter-core in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (4.6.3)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (3.2.0)
Requirement already satisfied: terminado>=0.8.1 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.8.3)
Requirement already satisfied: Send2Trash in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.5.0)
Requirement already satisfied: prometheus-client in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.7.1)
Requirement already satisfied: jinja2 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (2.11.1)
Requirement already satisfied: pyzmq>=17 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (18.1.1)
Requirement already satisfied: nbconvert in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (5.6.1)
Requirement already satisfied: python-dateutil>=2.1 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from jupyter-client->ipykernel>=4.5.1->ipywidgets>=7.0.0->gmaps) (2.8.1)
Requirement already satisfied: attrs>=17.4.0 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (19.3.0)
Requirement already satisfied: importlib-metadata; python_version < "3.8" in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (1.5.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (0.16.0)
Requirement already satisfied: MarkupSafe>=0.23 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from jinja2->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.1.1)
Requirement already satisfied: defusedxml in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.6.0)
Requirement already satisfied: bleach in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (3.1.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (1.4.2)
Requirement already satisfied: entrypoints>=0.2.2 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.3)
Requirement already satisfied: testpath in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.4.4)
Requirement already satisfied: mistune<2,>=0.8.1 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.8.4)
Requirement already satisfied: zipp>=0.5 in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from importlib-metadata; python_version < "3.8"->jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets>=7.0.0->gmaps) (2.2.0)
Requirement already satisfied: webencodings in /opt/anaconda3/envs/PythonDataViz/lib/python3.6/site-packages (from bleach->nbconvert->notebook>=4.4.1->widgetsnbextension~=3.5.0->ipywidgets>=7.0.0->gmaps) (0.5.1)
Enabling notebook extension jupyter-gmaps/extension...
      - Validating: OK

In [3]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import pprint
import json

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [4]:
file = pd.read_csv("../Output/data.csv")
file.head()

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,moroni,-11.70,43.26,77.63,73,26,18.66,KM,1589651582
1,1,namatanai,-3.67,152.43,79.84,81,2,6.67,PG,1589651582
2,2,punta arenas,-53.15,-70.92,41.00,86,75,5.82,CL,1589651268
3,3,capilla de guadalupe,20.83,-102.58,77.05,19,0,11.07,MX,1589651583
4,4,hamilton,39.18,-84.53,75.99,78,90,6.82,US,1589651583

In [13]:
weather_data = file.drop(columns=["Unnamed: 0"])
weather_data

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,moroni,-11.70,43.26,77.63,73,26,18.66,KM,1589651582
1,namatanai,-3.67,152.43,79.84,81,2,6.67,PG,1589651582
2,punta arenas,-53.15,-70.92,41.00,86,75,5.82,CL,1589651268
3,capilla de guadalupe,20.83,-102.58,77.05,19,0,11.07,MX,1589651583
4,hamilton,39.18,-84.53,75.99,78,90,6.82,US,1589651583
...,...,...,...,...,...,...,...,...,...
566,chkalovskoye,44.84,133.04,48.85,94,53,2.30,RU,1589651706
567,petropavlivka,48.46,36.44,50.67,77,33,6.46,UA,1589651706
568,manado,1.49,124.85,77.00,94,20,1.12,ID,1589651707
569,kondinskoye,59.65,67.41,50.40,77,51,7.02,RU,1589651707
570,ketchikan,55.34,-131.65,53.60,71,90,5.82,US,1589651707

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [14]:
gmaps.configure(api_key = g_key)

In [15]:
locations = weather_data[['Lat', 'Lng']]
humidity = weather_data["Humidity"].astype(float)
#humidity

fig = gmaps.figure()

heatmap_layer = gmaps.heatmap_layer(locations, weights=humidity,
                                   dissipating=False, max_intensity=10,
                                   point_radius=1)

fig.add_layer(heatmap_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [16]:
#Narrow down the DataFrame to find your ideal weather condition. For example:
#A max temperature lower than 80 degrees but higher than 70.
#Wind speed less than 10 mph.
#Zero cloudiness.
#Drop any rows that don't contain all three conditions. You want to be sure the weather is ideal.

new_data= pd.DataFrame(weather_data, columns = ["City", "Max Temp", "Wind Speed", "Cloudiness"])

max_temp = (new_data["Max Temp"] <= 80) & (new_data["Max Temp"] > 70)
wind_speed = new_data["Wind Speed"] < 10
cloudiness = new_data["Cloudiness"] == 0

new_data[max_temp & wind_speed & cloudiness]

             City  Max Temp  Wind Speed  Cloudiness
124          yima     77.00        5.10           0
186      necochea     78.01        7.00           0
263    nkhotakota     70.47        6.17           0
274      masuguru     71.53        3.15           0
453      bardiyah     74.59        6.98           0
463       peruibe     72.64        4.36           0
481          ibra     78.96        2.62           0
509   otjimbingwe     70.81        1.30           0
511          buin     75.99        2.24           0
528      antonina     72.00        8.05           0
560  nueva italia     77.00        2.24           0

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [17]:
hotel_df = pd.DataFrame(weather_data, columns=["City", "Country", "Lat", "Lng"])

hotel_df["Hotel Name"] = ""
hotel_df

                     City Country    Lat     Lng Hotel Name
0                  moroni      KM -11.70   43.26
1               namatanai      PG  -3.67  152.43
2            punta arenas      CL -53.15  -70.92
3    capilla de guadalupe      MX  20.83 -102.58
4                hamilton      US  39.18  -84.53
..                    ...     ...    ...     ...        ...
566          chkalovskoye      RU  44.84  133.04
567         petropavlivka      UA  48.46   36.44
568                manado      ID   1.49  124.85
569           kondinskoye      RU  59.65   67.41
570             ketchikan      US  55.34 -131.65

[571 rows x 5 columns]

In [38]:

hotel_name = []
for index, row in hotel_df.iterrows():
    lat = row["Lat"]
    lng = row["Lng"]
    target_coordinates = f"{lat},{lng}"
    target_search = "hotel"
    target_radius = 5000
    target_type = "hotel"

    # set up a parameters dictionary
    params = {
        "location": target_coordinates,
        "keyword": target_search,
        "radius": target_radius,
        "type": target_type,
        "key": g_key
    }
    

    # base url
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # run a request using our params dictionary
    response = requests.get(base_url, params=params)
    hotel_data = response.json()
    #print(json.dumps(hotel_data, indent=4, sort_keys=True))
    try:
        hotelnames = hotel_data["results"][0]["name"]
        hotel_name.append(hotelnames)
    except IndexError: 
        hotel_name.append(np.nan)

In [39]:
hotel_name
len(hotel_name)

571

In [40]:
hotel_df["Hotel Names"] = hotel_name
hotel_df.dropna()
hotel_df.to_csv('hotel_export.csv')

In [41]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [42]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations)
fig.add_layer(markers)


# Display figure
fig

Figure(layout=FigureLayout(height='420px'))